/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flagright.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.flagright.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = AchDetails.Builder.class)
public final class AchDetails {
    private final Optional<String> routingNumber;

    private final Optional<String> accountNumber;

    private final Optional<Amount> accountBalance;

    private final Optional<String> bankName;

    private final Optional<String> name;

    private final Optional<Address> bankAddress;

    private final Optional<Address> address;

    private final Optional<CountryCode> countryOfNationality;

    private final Optional<CountryCode> countryOfResidence;

    private final Optional<String> beneficiaryName;

    private final Optional<String> emailId;

    private final Optional<List<Tag>> tags;

    private final Map<String, Object> additionalProperties;

    private AchDetails(
            Optional<String> routingNumber,
            Optional<String> accountNumber,
            Optional<Amount> accountBalance,
            Optional<String> bankName,
            Optional<String> name,
            Optional<Address> bankAddress,
            Optional<Address> address,
            Optional<CountryCode> countryOfNationality,
            Optional<CountryCode> countryOfResidence,
            Optional<String> beneficiaryName,
            Optional<String> emailId,
            Optional<List<Tag>> tags,
            Map<String, Object> additionalProperties) {
        this.routingNumber = routingNumber;
        this.accountNumber = accountNumber;
        this.accountBalance = accountBalance;
        this.bankName = bankName;
        this.name = name;
        this.bankAddress = bankAddress;
        this.address = address;
        this.countryOfNationality = countryOfNationality;
        this.countryOfResidence = countryOfResidence;
        this.beneficiaryName = beneficiaryName;
        this.emailId = emailId;
        this.tags = tags;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Routing number of the bank
     */
    @JsonProperty("routingNumber")
    public Optional<String> getRoutingNumber() {
        return routingNumber;
    }

    /**
     * @return Bank account number of the individual
     */
    @JsonProperty("accountNumber")
    public Optional<String> getAccountNumber() {
        return accountNumber;
    }

    @JsonProperty("accountBalance")
    public Optional<Amount> getAccountBalance() {
        return accountBalance;
    }

    /**
     * @return Name of the bank
     */
    @JsonProperty("bankName")
    public Optional<String> getBankName() {
        return bankName;
    }

    /**
     * @return Name of the account holder
     */
    @JsonProperty("name")
    public Optional<String> getName() {
        return name;
    }

    @JsonProperty("bankAddress")
    public Optional<Address> getBankAddress() {
        return bankAddress;
    }

    /**
     * @return Address of the account holder
     */
    @JsonProperty("address")
    public Optional<Address> getAddress() {
        return address;
    }

    @JsonProperty("countryOfNationality")
    public Optional<CountryCode> getCountryOfNationality() {
        return countryOfNationality;
    }

    @JsonProperty("countryOfResidence")
    public Optional<CountryCode> getCountryOfResidence() {
        return countryOfResidence;
    }

    /**
     * @return Beneficiary name of the account
     */
    @JsonProperty("beneficiaryName")
    public Optional<String> getBeneficiaryName() {
        return beneficiaryName;
    }

    @JsonProperty("emailId")
    public Optional<String> getEmailId() {
        return emailId;
    }

    /**
     * @return Additional information that can be added via tags
     */
    @JsonProperty("tags")
    public Optional<List<Tag>> getTags() {
        return tags;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AchDetails && equalTo((AchDetails) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(AchDetails other) {
        return routingNumber.equals(other.routingNumber)
                && accountNumber.equals(other.accountNumber)
                && accountBalance.equals(other.accountBalance)
                && bankName.equals(other.bankName)
                && name.equals(other.name)
                && bankAddress.equals(other.bankAddress)
                && address.equals(other.address)
                && countryOfNationality.equals(other.countryOfNationality)
                && countryOfResidence.equals(other.countryOfResidence)
                && beneficiaryName.equals(other.beneficiaryName)
                && emailId.equals(other.emailId)
                && tags.equals(other.tags);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.routingNumber,
                this.accountNumber,
                this.accountBalance,
                this.bankName,
                this.name,
                this.bankAddress,
                this.address,
                this.countryOfNationality,
                this.countryOfResidence,
                this.beneficiaryName,
                this.emailId,
                this.tags);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> routingNumber = Optional.empty();

        private Optional<String> accountNumber = Optional.empty();

        private Optional<Amount> accountBalance = Optional.empty();

        private Optional<String> bankName = Optional.empty();

        private Optional<String> name = Optional.empty();

        private Optional<Address> bankAddress = Optional.empty();

        private Optional<Address> address = Optional.empty();

        private Optional<CountryCode> countryOfNationality = Optional.empty();

        private Optional<CountryCode> countryOfResidence = Optional.empty();

        private Optional<String> beneficiaryName = Optional.empty();

        private Optional<String> emailId = Optional.empty();

        private Optional<List<Tag>> tags = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(AchDetails other) {
            routingNumber(other.getRoutingNumber());
            accountNumber(other.getAccountNumber());
            accountBalance(other.getAccountBalance());
            bankName(other.getBankName());
            name(other.getName());
            bankAddress(other.getBankAddress());
            address(other.getAddress());
            countryOfNationality(other.getCountryOfNationality());
            countryOfResidence(other.getCountryOfResidence());
            beneficiaryName(other.getBeneficiaryName());
            emailId(other.getEmailId());
            tags(other.getTags());
            return this;
        }

        @JsonSetter(value = "routingNumber", nulls = Nulls.SKIP)
        public Builder routingNumber(Optional<String> routingNumber) {
            this.routingNumber = routingNumber;
            return this;
        }

        public Builder routingNumber(String routingNumber) {
            this.routingNumber = Optional.ofNullable(routingNumber);
            return this;
        }

        @JsonSetter(value = "accountNumber", nulls = Nulls.SKIP)
        public Builder accountNumber(Optional<String> accountNumber) {
            this.accountNumber = accountNumber;
            return this;
        }

        public Builder accountNumber(String accountNumber) {
            this.accountNumber = Optional.ofNullable(accountNumber);
            return this;
        }

        @JsonSetter(value = "accountBalance", nulls = Nulls.SKIP)
        public Builder accountBalance(Optional<Amount> accountBalance) {
            this.accountBalance = accountBalance;
            return this;
        }

        public Builder accountBalance(Amount accountBalance) {
            this.accountBalance = Optional.ofNullable(accountBalance);
            return this;
        }

        @JsonSetter(value = "bankName", nulls = Nulls.SKIP)
        public Builder bankName(Optional<String> bankName) {
            this.bankName = bankName;
            return this;
        }

        public Builder bankName(String bankName) {
            this.bankName = Optional.ofNullable(bankName);
            return this;
        }

        @JsonSetter(value = "name", nulls = Nulls.SKIP)
        public Builder name(Optional<String> name) {
            this.name = name;
            return this;
        }

        public Builder name(String name) {
            this.name = Optional.ofNullable(name);
            return this;
        }

        @JsonSetter(value = "bankAddress", nulls = Nulls.SKIP)
        public Builder bankAddress(Optional<Address> bankAddress) {
            this.bankAddress = bankAddress;
            return this;
        }

        public Builder bankAddress(Address bankAddress) {
            this.bankAddress = Optional.ofNullable(bankAddress);
            return this;
        }

        @JsonSetter(value = "address", nulls = Nulls.SKIP)
        public Builder address(Optional<Address> address) {
            this.address = address;
            return this;
        }

        public Builder address(Address address) {
            this.address = Optional.ofNullable(address);
            return this;
        }

        @JsonSetter(value = "countryOfNationality", nulls = Nulls.SKIP)
        public Builder countryOfNationality(Optional<CountryCode> countryOfNationality) {
            this.countryOfNationality = countryOfNationality;
            return this;
        }

        public Builder countryOfNationality(CountryCode countryOfNationality) {
            this.countryOfNationality = Optional.ofNullable(countryOfNationality);
            return this;
        }

        @JsonSetter(value = "countryOfResidence", nulls = Nulls.SKIP)
        public Builder countryOfResidence(Optional<CountryCode> countryOfResidence) {
            this.countryOfResidence = countryOfResidence;
            return this;
        }

        public Builder countryOfResidence(CountryCode countryOfResidence) {
            this.countryOfResidence = Optional.ofNullable(countryOfResidence);
            return this;
        }

        @JsonSetter(value = "beneficiaryName", nulls = Nulls.SKIP)
        public Builder beneficiaryName(Optional<String> beneficiaryName) {
            this.beneficiaryName = beneficiaryName;
            return this;
        }

        public Builder beneficiaryName(String beneficiaryName) {
            this.beneficiaryName = Optional.ofNullable(beneficiaryName);
            return this;
        }

        @JsonSetter(value = "emailId", nulls = Nulls.SKIP)
        public Builder emailId(Optional<String> emailId) {
            this.emailId = emailId;
            return this;
        }

        public Builder emailId(String emailId) {
            this.emailId = Optional.ofNullable(emailId);
            return this;
        }

        @JsonSetter(value = "tags", nulls = Nulls.SKIP)
        public Builder tags(Optional<List<Tag>> tags) {
            this.tags = tags;
            return this;
        }

        public Builder tags(List<Tag> tags) {
            this.tags = Optional.ofNullable(tags);
            return this;
        }

        public AchDetails build() {
            return new AchDetails(
                    routingNumber,
                    accountNumber,
                    accountBalance,
                    bankName,
                    name,
                    bankAddress,
                    address,
                    countryOfNationality,
                    countryOfResidence,
                    beneficiaryName,
                    emailId,
                    tags,
                    additionalProperties);
        }
    }
}
