/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flagright.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.flagright.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = BatchResponseFailedRecord.Builder.class)
public final class BatchResponseFailedRecord {
    private final Optional<String> id;

    private final Optional<String> reasonCode;

    private final Map<String, Object> additionalProperties;

    private BatchResponseFailedRecord(
            Optional<String> id, Optional<String> reasonCode, Map<String, Object> additionalProperties) {
        this.id = id;
        this.reasonCode = reasonCode;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("id")
    public Optional<String> getId() {
        return id;
    }

    @JsonProperty("reasonCode")
    public Optional<String> getReasonCode() {
        return reasonCode;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof BatchResponseFailedRecord && equalTo((BatchResponseFailedRecord) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(BatchResponseFailedRecord other) {
        return id.equals(other.id) && reasonCode.equals(other.reasonCode);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.reasonCode);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> id = Optional.empty();

        private Optional<String> reasonCode = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(BatchResponseFailedRecord other) {
            id(other.getId());
            reasonCode(other.getReasonCode());
            return this;
        }

        @JsonSetter(value = "id", nulls = Nulls.SKIP)
        public Builder id(Optional<String> id) {
            this.id = id;
            return this;
        }

        public Builder id(String id) {
            this.id = Optional.ofNullable(id);
            return this;
        }

        @JsonSetter(value = "reasonCode", nulls = Nulls.SKIP)
        public Builder reasonCode(Optional<String> reasonCode) {
            this.reasonCode = reasonCode;
            return this;
        }

        public Builder reasonCode(String reasonCode) {
            this.reasonCode = Optional.ofNullable(reasonCode);
            return this;
        }

        public BatchResponseFailedRecord build() {
            return new BatchResponseFailedRecord(id, reasonCode, additionalProperties);
        }
    }
}
