/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flagright.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.flagright.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = BlockchainCounterparty.Builder.class)
public final class BlockchainCounterparty {
    private final Optional<String> name;

    private final Optional<String> categoryId;

    private final Map<String, Object> additionalProperties;

    private BlockchainCounterparty(
            Optional<String> name, Optional<String> categoryId, Map<String, Object> additionalProperties) {
        this.name = name;
        this.categoryId = categoryId;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Name of the counterparty (e.g., exchange name)
     */
    @JsonProperty("name")
    public Optional<String> getName() {
        return name;
    }

    /**
     * @return Category identifier for the counterparty
     */
    @JsonProperty("categoryId")
    public Optional<String> getCategoryId() {
        return categoryId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof BlockchainCounterparty && equalTo((BlockchainCounterparty) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(BlockchainCounterparty other) {
        return name.equals(other.name) && categoryId.equals(other.categoryId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.name, this.categoryId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> name = Optional.empty();

        private Optional<String> categoryId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(BlockchainCounterparty other) {
            name(other.getName());
            categoryId(other.getCategoryId());
            return this;
        }

        @JsonSetter(value = "name", nulls = Nulls.SKIP)
        public Builder name(Optional<String> name) {
            this.name = name;
            return this;
        }

        public Builder name(String name) {
            this.name = Optional.ofNullable(name);
            return this;
        }

        @JsonSetter(value = "categoryId", nulls = Nulls.SKIP)
        public Builder categoryId(Optional<String> categoryId) {
            this.categoryId = categoryId;
            return this;
        }

        public Builder categoryId(String categoryId) {
            this.categoryId = Optional.ofNullable(categoryId);
            return this;
        }

        public BlockchainCounterparty build() {
            return new BlockchainCounterparty(name, categoryId, additionalProperties);
        }
    }
}
