/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flagright.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.flagright.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = BlockchainRiskDetail.Builder.class)
public final class BlockchainRiskDetail {
    private final Optional<String> alertId;

    private final Optional<String> categoryId;

    private final Optional<String> categoryName;

    private final Optional<RiskLevel> categoryRiskLevel;

    private final Optional<Double> categoryRiskScore;

    private final Optional<RiskExposureType> exposureType;

    private final Optional<String> entity;

    private final Optional<TransactionAmountDetails> exposureAmount;

    private final Map<String, Object> additionalProperties;

    private BlockchainRiskDetail(
            Optional<String> alertId,
            Optional<String> categoryId,
            Optional<String> categoryName,
            Optional<RiskLevel> categoryRiskLevel,
            Optional<Double> categoryRiskScore,
            Optional<RiskExposureType> exposureType,
            Optional<String> entity,
            Optional<TransactionAmountDetails> exposureAmount,
            Map<String, Object> additionalProperties) {
        this.alertId = alertId;
        this.categoryId = categoryId;
        this.categoryName = categoryName;
        this.categoryRiskLevel = categoryRiskLevel;
        this.categoryRiskScore = categoryRiskScore;
        this.exposureType = exposureType;
        this.entity = entity;
        this.exposureAmount = exposureAmount;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Optional alert identifier (alerts don't always exist)
     */
    @JsonProperty("alertId")
    public Optional<String> getAlertId() {
        return alertId;
    }

    /**
     * @return Unique identifier for the risk category
     */
    @JsonProperty("categoryId")
    public Optional<String> getCategoryId() {
        return categoryId;
    }

    /**
     * @return Human-readable name of the risk category
     */
    @JsonProperty("categoryName")
    public Optional<String> getCategoryName() {
        return categoryName;
    }

    /**
     * @return Risk level specific to this category
     */
    @JsonProperty("categoryRiskLevel")
    public Optional<RiskLevel> getCategoryRiskLevel() {
        return categoryRiskLevel;
    }

    /**
     * @return Numeric risk score for this specific category
     */
    @JsonProperty("categoryRiskScore")
    public Optional<Double> getCategoryRiskScore() {
        return categoryRiskScore;
    }

    /**
     * @return Type of exposure to the risk entity
     */
    @JsonProperty("exposureType")
    public Optional<RiskExposureType> getExposureType() {
        return exposureType;
    }

    /**
     * @return Name of the specific entity that poses the risk
     */
    @JsonProperty("entity")
    public Optional<String> getEntity() {
        return entity;
    }

    /**
     * @return Amount of the transaction exposed to this risk
     */
    @JsonProperty("exposureAmount")
    public Optional<TransactionAmountDetails> getExposureAmount() {
        return exposureAmount;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof BlockchainRiskDetail && equalTo((BlockchainRiskDetail) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(BlockchainRiskDetail other) {
        return alertId.equals(other.alertId)
                && categoryId.equals(other.categoryId)
                && categoryName.equals(other.categoryName)
                && categoryRiskLevel.equals(other.categoryRiskLevel)
                && categoryRiskScore.equals(other.categoryRiskScore)
                && exposureType.equals(other.exposureType)
                && entity.equals(other.entity)
                && exposureAmount.equals(other.exposureAmount);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.alertId,
                this.categoryId,
                this.categoryName,
                this.categoryRiskLevel,
                this.categoryRiskScore,
                this.exposureType,
                this.entity,
                this.exposureAmount);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> alertId = Optional.empty();

        private Optional<String> categoryId = Optional.empty();

        private Optional<String> categoryName = Optional.empty();

        private Optional<RiskLevel> categoryRiskLevel = Optional.empty();

        private Optional<Double> categoryRiskScore = Optional.empty();

        private Optional<RiskExposureType> exposureType = Optional.empty();

        private Optional<String> entity = Optional.empty();

        private Optional<TransactionAmountDetails> exposureAmount = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(BlockchainRiskDetail other) {
            alertId(other.getAlertId());
            categoryId(other.getCategoryId());
            categoryName(other.getCategoryName());
            categoryRiskLevel(other.getCategoryRiskLevel());
            categoryRiskScore(other.getCategoryRiskScore());
            exposureType(other.getExposureType());
            entity(other.getEntity());
            exposureAmount(other.getExposureAmount());
            return this;
        }

        @JsonSetter(value = "alertId", nulls = Nulls.SKIP)
        public Builder alertId(Optional<String> alertId) {
            this.alertId = alertId;
            return this;
        }

        public Builder alertId(String alertId) {
            this.alertId = Optional.ofNullable(alertId);
            return this;
        }

        @JsonSetter(value = "categoryId", nulls = Nulls.SKIP)
        public Builder categoryId(Optional<String> categoryId) {
            this.categoryId = categoryId;
            return this;
        }

        public Builder categoryId(String categoryId) {
            this.categoryId = Optional.ofNullable(categoryId);
            return this;
        }

        @JsonSetter(value = "categoryName", nulls = Nulls.SKIP)
        public Builder categoryName(Optional<String> categoryName) {
            this.categoryName = categoryName;
            return this;
        }

        public Builder categoryName(String categoryName) {
            this.categoryName = Optional.ofNullable(categoryName);
            return this;
        }

        @JsonSetter(value = "categoryRiskLevel", nulls = Nulls.SKIP)
        public Builder categoryRiskLevel(Optional<RiskLevel> categoryRiskLevel) {
            this.categoryRiskLevel = categoryRiskLevel;
            return this;
        }

        public Builder categoryRiskLevel(RiskLevel categoryRiskLevel) {
            this.categoryRiskLevel = Optional.ofNullable(categoryRiskLevel);
            return this;
        }

        @JsonSetter(value = "categoryRiskScore", nulls = Nulls.SKIP)
        public Builder categoryRiskScore(Optional<Double> categoryRiskScore) {
            this.categoryRiskScore = categoryRiskScore;
            return this;
        }

        public Builder categoryRiskScore(Double categoryRiskScore) {
            this.categoryRiskScore = Optional.ofNullable(categoryRiskScore);
            return this;
        }

        @JsonSetter(value = "exposureType", nulls = Nulls.SKIP)
        public Builder exposureType(Optional<RiskExposureType> exposureType) {
            this.exposureType = exposureType;
            return this;
        }

        public Builder exposureType(RiskExposureType exposureType) {
            this.exposureType = Optional.ofNullable(exposureType);
            return this;
        }

        @JsonSetter(value = "entity", nulls = Nulls.SKIP)
        public Builder entity(Optional<String> entity) {
            this.entity = entity;
            return this;
        }

        public Builder entity(String entity) {
            this.entity = Optional.ofNullable(entity);
            return this;
        }

        @JsonSetter(value = "exposureAmount", nulls = Nulls.SKIP)
        public Builder exposureAmount(Optional<TransactionAmountDetails> exposureAmount) {
            this.exposureAmount = exposureAmount;
            return this;
        }

        public Builder exposureAmount(TransactionAmountDetails exposureAmount) {
            this.exposureAmount = Optional.ofNullable(exposureAmount);
            return this;
        }

        public BlockchainRiskDetail build() {
            return new BlockchainRiskDetail(
                    alertId,
                    categoryId,
                    categoryName,
                    categoryRiskLevel,
                    categoryRiskScore,
                    exposureType,
                    entity,
                    exposureAmount,
                    additionalProperties);
        }
    }
}
