/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flagright.api.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum BlockchainRiskSubjectType {
    ADDRESS("ADDRESS"),

    TRANSACTION("TRANSACTION"),

    SMART_CONTRACT("SMART_CONTRACT"),

    ENTITY("ENTITY");

    private final String value;

    BlockchainRiskSubjectType(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
