/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flagright.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.flagright.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = BlockchainRiskSubject.Builder.class)
public final class BlockchainRiskSubject {
    private final Optional<BlockchainRiskSubjectType> type;

    private final Optional<String> value;

    private final Optional<BlockchainRiskSubjectDirection> direction;

    private final Optional<List<Tag>> tags;

    private final Map<String, Object> additionalProperties;

    private BlockchainRiskSubject(
            Optional<BlockchainRiskSubjectType> type,
            Optional<String> value,
            Optional<BlockchainRiskSubjectDirection> direction,
            Optional<List<Tag>> tags,
            Map<String, Object> additionalProperties) {
        this.type = type;
        this.value = value;
        this.direction = direction;
        this.tags = tags;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Type of the subject being analyzed
     */
    @JsonProperty("type")
    public Optional<BlockchainRiskSubjectType> getType() {
        return type;
    }

    /**
     * @return Single canonical value for the subject (e.g., address hash)
     */
    @JsonProperty("value")
    public Optional<String> getValue() {
        return value;
    }

    /**
     * @return Direction of the subject in the transaction (maps to origin/destination)
     */
    @JsonProperty("direction")
    public Optional<BlockchainRiskSubjectDirection> getDirection() {
        return direction;
    }

    /**
     * @return Additional information that can be added via tags
     */
    @JsonProperty("tags")
    public Optional<List<Tag>> getTags() {
        return tags;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof BlockchainRiskSubject && equalTo((BlockchainRiskSubject) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(BlockchainRiskSubject other) {
        return type.equals(other.type)
                && value.equals(other.value)
                && direction.equals(other.direction)
                && tags.equals(other.tags);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.type, this.value, this.direction, this.tags);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<BlockchainRiskSubjectType> type = Optional.empty();

        private Optional<String> value = Optional.empty();

        private Optional<BlockchainRiskSubjectDirection> direction = Optional.empty();

        private Optional<List<Tag>> tags = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(BlockchainRiskSubject other) {
            type(other.getType());
            value(other.getValue());
            direction(other.getDirection());
            tags(other.getTags());
            return this;
        }

        @JsonSetter(value = "type", nulls = Nulls.SKIP)
        public Builder type(Optional<BlockchainRiskSubjectType> type) {
            this.type = type;
            return this;
        }

        public Builder type(BlockchainRiskSubjectType type) {
            this.type = Optional.ofNullable(type);
            return this;
        }

        @JsonSetter(value = "value", nulls = Nulls.SKIP)
        public Builder value(Optional<String> value) {
            this.value = value;
            return this;
        }

        public Builder value(String value) {
            this.value = Optional.ofNullable(value);
            return this;
        }

        @JsonSetter(value = "direction", nulls = Nulls.SKIP)
        public Builder direction(Optional<BlockchainRiskSubjectDirection> direction) {
            this.direction = direction;
            return this;
        }

        public Builder direction(BlockchainRiskSubjectDirection direction) {
            this.direction = Optional.ofNullable(direction);
            return this;
        }

        @JsonSetter(value = "tags", nulls = Nulls.SKIP)
        public Builder tags(Optional<List<Tag>> tags) {
            this.tags = tags;
            return this;
        }

        public Builder tags(List<Tag> tags) {
            this.tags = Optional.ofNullable(tags);
            return this;
        }

        public BlockchainRiskSubject build() {
            return new BlockchainRiskSubject(type, value, direction, tags, additionalProperties);
        }
    }
}
