/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flagright.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.flagright.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = BlockchainRisk.Builder.class)
public final class BlockchainRisk {
    private final Optional<String> provider;

    private final Optional<Double> timestamp;

    private final Optional<RiskLevel> riskLevel;

    private final Optional<Double> riskScore;

    private final Optional<List<BlockchainCounterparty>> counterparties;

    private final Optional<BlockchainRiskSubject> subject;

    private final Optional<List<BlockchainRiskDetail>> risks;

    private final Optional<List<Tag>> tags;

    private final Map<String, Object> additionalProperties;

    private BlockchainRisk(
            Optional<String> provider,
            Optional<Double> timestamp,
            Optional<RiskLevel> riskLevel,
            Optional<Double> riskScore,
            Optional<List<BlockchainCounterparty>> counterparties,
            Optional<BlockchainRiskSubject> subject,
            Optional<List<BlockchainRiskDetail>> risks,
            Optional<List<Tag>> tags,
            Map<String, Object> additionalProperties) {
        this.provider = provider;
        this.timestamp = timestamp;
        this.riskLevel = riskLevel;
        this.riskScore = riskScore;
        this.counterparties = counterparties;
        this.subject = subject;
        this.risks = risks;
        this.tags = tags;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Risk analysis provider (e.g., chainalysis)
     */
    @JsonProperty("provider")
    public Optional<String> getProvider() {
        return provider;
    }

    /**
     * @return Unix timestamp of when the risk analysis was performed
     */
    @JsonProperty("timestamp")
    public Optional<Double> getTimestamp() {
        return timestamp;
    }

    /**
     * @return Overall risk level of the transaction
     */
    @JsonProperty("riskLevel")
    public Optional<RiskLevel> getRiskLevel() {
        return riskLevel;
    }

    /**
     * @return Numeric risk score from 0 to 100
     */
    @JsonProperty("riskScore")
    public Optional<Double> getRiskScore() {
        return riskScore;
    }

    /**
     * @return List of counterparties involved in the transaction
     */
    @JsonProperty("counterparties")
    public Optional<List<BlockchainCounterparty>> getCounterparties() {
        return counterparties;
    }

    /**
     * @return Subject of the risk analysis (address, transaction, entity, or smart contract)
     */
    @JsonProperty("subject")
    public Optional<BlockchainRiskSubject> getSubject() {
        return subject;
    }

    /**
     * @return Detailed risk categories and their analysis
     */
    @JsonProperty("risks")
    public Optional<List<BlockchainRiskDetail>> getRisks() {
        return risks;
    }

    /**
     * @return Additional information that can be added via tags
     */
    @JsonProperty("tags")
    public Optional<List<Tag>> getTags() {
        return tags;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof BlockchainRisk && equalTo((BlockchainRisk) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(BlockchainRisk other) {
        return provider.equals(other.provider)
                && timestamp.equals(other.timestamp)
                && riskLevel.equals(other.riskLevel)
                && riskScore.equals(other.riskScore)
                && counterparties.equals(other.counterparties)
                && subject.equals(other.subject)
                && risks.equals(other.risks)
                && tags.equals(other.tags);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.provider,
                this.timestamp,
                this.riskLevel,
                this.riskScore,
                this.counterparties,
                this.subject,
                this.risks,
                this.tags);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> provider = Optional.empty();

        private Optional<Double> timestamp = Optional.empty();

        private Optional<RiskLevel> riskLevel = Optional.empty();

        private Optional<Double> riskScore = Optional.empty();

        private Optional<List<BlockchainCounterparty>> counterparties = Optional.empty();

        private Optional<BlockchainRiskSubject> subject = Optional.empty();

        private Optional<List<BlockchainRiskDetail>> risks = Optional.empty();

        private Optional<List<Tag>> tags = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(BlockchainRisk other) {
            provider(other.getProvider());
            timestamp(other.getTimestamp());
            riskLevel(other.getRiskLevel());
            riskScore(other.getRiskScore());
            counterparties(other.getCounterparties());
            subject(other.getSubject());
            risks(other.getRisks());
            tags(other.getTags());
            return this;
        }

        @JsonSetter(value = "provider", nulls = Nulls.SKIP)
        public Builder provider(Optional<String> provider) {
            this.provider = provider;
            return this;
        }

        public Builder provider(String provider) {
            this.provider = Optional.ofNullable(provider);
            return this;
        }

        @JsonSetter(value = "timestamp", nulls = Nulls.SKIP)
        public Builder timestamp(Optional<Double> timestamp) {
            this.timestamp = timestamp;
            return this;
        }

        public Builder timestamp(Double timestamp) {
            this.timestamp = Optional.ofNullable(timestamp);
            return this;
        }

        @JsonSetter(value = "riskLevel", nulls = Nulls.SKIP)
        public Builder riskLevel(Optional<RiskLevel> riskLevel) {
            this.riskLevel = riskLevel;
            return this;
        }

        public Builder riskLevel(RiskLevel riskLevel) {
            this.riskLevel = Optional.ofNullable(riskLevel);
            return this;
        }

        @JsonSetter(value = "riskScore", nulls = Nulls.SKIP)
        public Builder riskScore(Optional<Double> riskScore) {
            this.riskScore = riskScore;
            return this;
        }

        public Builder riskScore(Double riskScore) {
            this.riskScore = Optional.ofNullable(riskScore);
            return this;
        }

        @JsonSetter(value = "counterparties", nulls = Nulls.SKIP)
        public Builder counterparties(Optional<List<BlockchainCounterparty>> counterparties) {
            this.counterparties = counterparties;
            return this;
        }

        public Builder counterparties(List<BlockchainCounterparty> counterparties) {
            this.counterparties = Optional.ofNullable(counterparties);
            return this;
        }

        @JsonSetter(value = "subject", nulls = Nulls.SKIP)
        public Builder subject(Optional<BlockchainRiskSubject> subject) {
            this.subject = subject;
            return this;
        }

        public Builder subject(BlockchainRiskSubject subject) {
            this.subject = Optional.ofNullable(subject);
            return this;
        }

        @JsonSetter(value = "risks", nulls = Nulls.SKIP)
        public Builder risks(Optional<List<BlockchainRiskDetail>> risks) {
            this.risks = risks;
            return this;
        }

        public Builder risks(List<BlockchainRiskDetail> risks) {
            this.risks = Optional.ofNullable(risks);
            return this;
        }

        @JsonSetter(value = "tags", nulls = Nulls.SKIP)
        public Builder tags(Optional<List<Tag>> tags) {
            this.tags = tags;
            return this;
        }

        public Builder tags(List<Tag> tags) {
            this.tags = Optional.ofNullable(tags);
            return this;
        }

        public BlockchainRisk build() {
            return new BlockchainRisk(
                    provider,
                    timestamp,
                    riskLevel,
                    riskScore,
                    counterparties,
                    subject,
                    risks,
                    tags,
                    additionalProperties);
        }
    }
}
