/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flagright.api.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum CaseType {
    MANUAL("MANUAL"),

    SYSTEM("SYSTEM"),

    EXTERNAL("EXTERNAL");

    private final String value;

    CaseType(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
