/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flagright.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.flagright.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CorporateEntityDetails.Builder.class)
public final class CorporateEntityDetails {
    private final String legalName;

    private final Map<String, Object> additionalProperties;

    private CorporateEntityDetails(String legalName, Map<String, Object> additionalProperties) {
        this.legalName = legalName;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Legal name of the corporate entity
     */
    @JsonProperty("legalName")
    public String getLegalName() {
        return legalName;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CorporateEntityDetails && equalTo((CorporateEntityDetails) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CorporateEntityDetails other) {
        return legalName.equals(other.legalName);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.legalName);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static LegalNameStage builder() {
        return new Builder();
    }

    public interface LegalNameStage {
        _FinalStage legalName(@NotNull String legalName);

        Builder from(CorporateEntityDetails other);
    }

    public interface _FinalStage {
        CorporateEntityDetails build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements LegalNameStage, _FinalStage {
        private String legalName;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CorporateEntityDetails other) {
            legalName(other.getLegalName());
            return this;
        }

        /**
         * <p>Legal name of the corporate entity</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("legalName")
        public _FinalStage legalName(@NotNull String legalName) {
            this.legalName = Objects.requireNonNull(legalName, "legalName must not be null");
            return this;
        }

        @java.lang.Override
        public CorporateEntityDetails build() {
            return new CorporateEntityDetails(legalName, additionalProperties);
        }
    }
}
