/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flagright.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.flagright.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CraRiskLevelUpdatedDetails.Builder.class)
public final class CraRiskLevelUpdatedDetails {
    private final Optional<String> riskLevel;

    private final Optional<Double> riskScore;

    private final Optional<String> type;

    private final Optional<String> userId;

    private final Map<String, Object> additionalProperties;

    private CraRiskLevelUpdatedDetails(
            Optional<String> riskLevel,
            Optional<Double> riskScore,
            Optional<String> type,
            Optional<String> userId,
            Map<String, Object> additionalProperties) {
        this.riskLevel = riskLevel;
        this.riskScore = riskScore;
        this.type = type;
        this.userId = userId;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("riskLevel")
    public Optional<String> getRiskLevel() {
        return riskLevel;
    }

    @JsonProperty("riskScore")
    public Optional<Double> getRiskScore() {
        return riskScore;
    }

    @JsonProperty("type")
    public Optional<String> getType() {
        return type;
    }

    @JsonProperty("userId")
    public Optional<String> getUserId() {
        return userId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CraRiskLevelUpdatedDetails && equalTo((CraRiskLevelUpdatedDetails) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CraRiskLevelUpdatedDetails other) {
        return riskLevel.equals(other.riskLevel)
                && riskScore.equals(other.riskScore)
                && type.equals(other.type)
                && userId.equals(other.userId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.riskLevel, this.riskScore, this.type, this.userId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> riskLevel = Optional.empty();

        private Optional<Double> riskScore = Optional.empty();

        private Optional<String> type = Optional.empty();

        private Optional<String> userId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(CraRiskLevelUpdatedDetails other) {
            riskLevel(other.getRiskLevel());
            riskScore(other.getRiskScore());
            type(other.getType());
            userId(other.getUserId());
            return this;
        }

        @JsonSetter(value = "riskLevel", nulls = Nulls.SKIP)
        public Builder riskLevel(Optional<String> riskLevel) {
            this.riskLevel = riskLevel;
            return this;
        }

        public Builder riskLevel(String riskLevel) {
            this.riskLevel = Optional.ofNullable(riskLevel);
            return this;
        }

        @JsonSetter(value = "riskScore", nulls = Nulls.SKIP)
        public Builder riskScore(Optional<Double> riskScore) {
            this.riskScore = riskScore;
            return this;
        }

        public Builder riskScore(Double riskScore) {
            this.riskScore = Optional.ofNullable(riskScore);
            return this;
        }

        @JsonSetter(value = "type", nulls = Nulls.SKIP)
        public Builder type(Optional<String> type) {
            this.type = type;
            return this;
        }

        public Builder type(String type) {
            this.type = Optional.ofNullable(type);
            return this;
        }

        @JsonSetter(value = "userId", nulls = Nulls.SKIP)
        public Builder userId(Optional<String> userId) {
            this.userId = userId;
            return this;
        }

        public Builder userId(String userId) {
            this.userId = Optional.ofNullable(userId);
            return this;
        }

        public CraRiskLevelUpdatedDetails build() {
            return new CraRiskLevelUpdatedDetails(riskLevel, riskScore, type, userId, additionalProperties);
        }
    }
}
