/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flagright.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.flagright.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CraRiskLevelUpdatedRiskFactor.Builder.class)
public final class CraRiskLevelUpdatedRiskFactor {
    private final Optional<String> riskFactorId;

    private final Optional<String> riskFactorVersionId;

    private final Optional<String> value;

    private final Optional<Double> riskScore;

    private final Optional<String> riskLevel;

    private final Optional<Double> weight;

    private final Map<String, Object> additionalProperties;

    private CraRiskLevelUpdatedRiskFactor(
            Optional<String> riskFactorId,
            Optional<String> riskFactorVersionId,
            Optional<String> value,
            Optional<Double> riskScore,
            Optional<String> riskLevel,
            Optional<Double> weight,
            Map<String, Object> additionalProperties) {
        this.riskFactorId = riskFactorId;
        this.riskFactorVersionId = riskFactorVersionId;
        this.value = value;
        this.riskScore = riskScore;
        this.riskLevel = riskLevel;
        this.weight = weight;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("riskFactorId")
    public Optional<String> getRiskFactorId() {
        return riskFactorId;
    }

    /**
     * @return Set for KRS factor score detail rows
     */
    @JsonProperty("riskFactorVersionId")
    public Optional<String> getRiskFactorVersionId() {
        return riskFactorVersionId;
    }

    @JsonProperty("value")
    public Optional<String> getValue() {
        return value;
    }

    @JsonProperty("riskScore")
    public Optional<Double> getRiskScore() {
        return riskScore;
    }

    @JsonProperty("riskLevel")
    public Optional<String> getRiskLevel() {
        return riskLevel;
    }

    @JsonProperty("weight")
    public Optional<Double> getWeight() {
        return weight;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CraRiskLevelUpdatedRiskFactor && equalTo((CraRiskLevelUpdatedRiskFactor) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CraRiskLevelUpdatedRiskFactor other) {
        return riskFactorId.equals(other.riskFactorId)
                && riskFactorVersionId.equals(other.riskFactorVersionId)
                && value.equals(other.value)
                && riskScore.equals(other.riskScore)
                && riskLevel.equals(other.riskLevel)
                && weight.equals(other.weight);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.riskFactorId, this.riskFactorVersionId, this.value, this.riskScore, this.riskLevel, this.weight);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> riskFactorId = Optional.empty();

        private Optional<String> riskFactorVersionId = Optional.empty();

        private Optional<String> value = Optional.empty();

        private Optional<Double> riskScore = Optional.empty();

        private Optional<String> riskLevel = Optional.empty();

        private Optional<Double> weight = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(CraRiskLevelUpdatedRiskFactor other) {
            riskFactorId(other.getRiskFactorId());
            riskFactorVersionId(other.getRiskFactorVersionId());
            value(other.getValue());
            riskScore(other.getRiskScore());
            riskLevel(other.getRiskLevel());
            weight(other.getWeight());
            return this;
        }

        @JsonSetter(value = "riskFactorId", nulls = Nulls.SKIP)
        public Builder riskFactorId(Optional<String> riskFactorId) {
            this.riskFactorId = riskFactorId;
            return this;
        }

        public Builder riskFactorId(String riskFactorId) {
            this.riskFactorId = Optional.ofNullable(riskFactorId);
            return this;
        }

        @JsonSetter(value = "riskFactorVersionId", nulls = Nulls.SKIP)
        public Builder riskFactorVersionId(Optional<String> riskFactorVersionId) {
            this.riskFactorVersionId = riskFactorVersionId;
            return this;
        }

        public Builder riskFactorVersionId(String riskFactorVersionId) {
            this.riskFactorVersionId = Optional.ofNullable(riskFactorVersionId);
            return this;
        }

        @JsonSetter(value = "value", nulls = Nulls.SKIP)
        public Builder value(Optional<String> value) {
            this.value = value;
            return this;
        }

        public Builder value(String value) {
            this.value = Optional.ofNullable(value);
            return this;
        }

        @JsonSetter(value = "riskScore", nulls = Nulls.SKIP)
        public Builder riskScore(Optional<Double> riskScore) {
            this.riskScore = riskScore;
            return this;
        }

        public Builder riskScore(Double riskScore) {
            this.riskScore = Optional.ofNullable(riskScore);
            return this;
        }

        @JsonSetter(value = "riskLevel", nulls = Nulls.SKIP)
        public Builder riskLevel(Optional<String> riskLevel) {
            this.riskLevel = riskLevel;
            return this;
        }

        public Builder riskLevel(String riskLevel) {
            this.riskLevel = Optional.ofNullable(riskLevel);
            return this;
        }

        @JsonSetter(value = "weight", nulls = Nulls.SKIP)
        public Builder weight(Optional<Double> weight) {
            this.weight = weight;
            return this;
        }

        public Builder weight(Double weight) {
            this.weight = Optional.ofNullable(weight);
            return this;
        }

        public CraRiskLevelUpdatedRiskFactor build() {
            return new CraRiskLevelUpdatedRiskFactor(
                    riskFactorId, riskFactorVersionId, value, riskScore, riskLevel, weight, additionalProperties);
        }
    }
}
