/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flagright.api.types;

import java.util.List;
import java.util.Optional;

public interface IBusinessWithRulesResult {
    String getUserId();

    double getCreatedTimestamp();

    LegalEntity getLegalEntity();

    Optional<Double> getActivatedTimestamp();

    Optional<UserStateDetails> getUserStateDetails();

    Optional<KycStatusDetails> getKycStatusDetails();

    Optional<Double> getEoddDate();

    Optional<List<CorporateEntityDetails>> getCorporateEntities();

    Optional<List<BusinessWithRulesResultShareHoldersItem>> getShareHolders();

    Optional<List<BusinessWithRulesResultDirectorsItem>> getDirectors();

    Optional<List<BusinessWithRulesResultAssociatedPartiesItem>> getAssociatedParties();

    Optional<List<LegalEntity>> getBusinessPartners();

    Optional<TransactionLimits> getTransactionLimits();

    Optional<ExpectedTransactionCountries> getExpectedTransactionCountries();

    Optional<ExpectedTransactionCurrencies> getExpectedTransactionCurrencies();

    Optional<RiskLevel> getRiskLevel();

    Optional<RiskLevel> getKycRiskLevel();

    Optional<List<PaymentMethod>> getAllowedPaymentMethods();

    Optional<UserEntityLink> getLinkedEntities();

    Optional<AcquisitionChannel> getAcquisitionChannel();

    Optional<List<BusinessWithRulesResultSavedPaymentDetailsItem>> getSavedPaymentDetails();

    Optional<MccDetails> getMccDetails();

    Optional<List<UserTag>> getTags();

    Optional<List<PersonAttachment>> getAttachments();

    Optional<DeviceData> getMetaData();

    Optional<String> getJurisdiction();

    Optional<List<ProductsEnabled>> getProductsEnabled();

    Optional<List<PepStatus>> getPepStatus();

    Optional<Boolean> getSanctionsStatus();

    Optional<Boolean> getAdverseMediaStatus();

    Optional<List<String>> getExternalLinks();

    Optional<List<ExecutedRulesResult>> getExecutedRules();

    Optional<List<HitRulesDetails>> getHitRules();

    Optional<UserRiskScoreDetails> getRiskScoreDetails();
}
