/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flagright.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.flagright.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PosDetails.Builder.class)
public final class PosDetails {
    private final Optional<PosEntryMode> entryMode;

    private final Map<String, Object> additionalProperties;

    private PosDetails(Optional<PosEntryMode> entryMode, Map<String, Object> additionalProperties) {
        this.entryMode = entryMode;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("entryMode")
    public Optional<PosEntryMode> getEntryMode() {
        return entryMode;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PosDetails && equalTo((PosDetails) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PosDetails other) {
        return entryMode.equals(other.entryMode);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.entryMode);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<PosEntryMode> entryMode = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(PosDetails other) {
            entryMode(other.getEntryMode());
            return this;
        }

        @JsonSetter(value = "entryMode", nulls = Nulls.SKIP)
        public Builder entryMode(Optional<PosEntryMode> entryMode) {
            this.entryMode = entryMode;
            return this;
        }

        public Builder entryMode(PosEntryMode entryMode) {
            this.entryMode = Optional.ofNullable(entryMode);
            return this;
        }

        public PosDetails build() {
            return new PosDetails(entryMode, additionalProperties);
        }
    }
}
