/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flagright.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.flagright.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ProductsEnabled.Builder.class)
public final class ProductsEnabled {
    private final Optional<String> productName;

    private final Map<String, Object> additionalProperties;

    private ProductsEnabled(Optional<String> productName, Map<String, Object> additionalProperties) {
        this.productName = productName;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("productName")
    public Optional<String> getProductName() {
        return productName;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ProductsEnabled && equalTo((ProductsEnabled) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ProductsEnabled other) {
        return productName.equals(other.productName);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.productName);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> productName = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ProductsEnabled other) {
            productName(other.getProductName());
            return this;
        }

        @JsonSetter(value = "productName", nulls = Nulls.SKIP)
        public Builder productName(Optional<String> productName) {
            this.productName = productName;
            return this;
        }

        public Builder productName(String productName) {
            this.productName = Optional.ofNullable(productName);
            return this;
        }

        public ProductsEnabled build() {
            return new ProductsEnabled(productName, additionalProperties);
        }
    }
}
