/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flagright.api.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum RuleNature {
    AML("AML"),

    FRAUD("FRAUD"),

    CTF("CTF"),

    SCREENING("SCREENING");

    private final String value;

    RuleNature(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
