/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flagright.api.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum TransactionType {
    DEPOSIT("DEPOSIT"),

    TRANSFER("TRANSFER"),

    EXTERNAL_PAYMENT("EXTERNAL_PAYMENT"),

    WITHDRAWAL("WITHDRAWAL"),

    REFUND("REFUND"),

    OTHER("OTHER");

    private final String value;

    TransactionType(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
