/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flagright.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.flagright.api.core.ObjectMappers;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TransactionMonitoringResult.Builder.class)
public final class TransactionMonitoringResult implements ITransactionMonitoringResult {
    private final String transactionId;

    private final RuleAction status;

    private final Optional<TransactionRiskScoringResult> riskScoreDetails;

    private final List<ExecutedRulesResult> executedRules;

    private final List<HitRulesDetails> hitRules;

    private final Map<String, Object> additionalProperties;

    private TransactionMonitoringResult(
            String transactionId,
            RuleAction status,
            Optional<TransactionRiskScoringResult> riskScoreDetails,
            List<ExecutedRulesResult> executedRules,
            List<HitRulesDetails> hitRules,
            Map<String, Object> additionalProperties) {
        this.transactionId = transactionId;
        this.status = status;
        this.riskScoreDetails = riskScoreDetails;
        this.executedRules = executedRules;
        this.hitRules = hitRules;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Transaction ID that the results pertain to
     */
    @JsonProperty("transactionId")
    @java.lang.Override
    public String getTransactionId() {
        return transactionId;
    }

    @JsonProperty("status")
    @java.lang.Override
    public RuleAction getStatus() {
        return status;
    }

    @JsonProperty("riskScoreDetails")
    @java.lang.Override
    public Optional<TransactionRiskScoringResult> getRiskScoreDetails() {
        return riskScoreDetails;
    }

    /**
     * @return Unique transaction identifier
     */
    @JsonProperty("executedRules")
    @java.lang.Override
    public List<ExecutedRulesResult> getExecutedRules() {
        return executedRules;
    }

    /**
     * @return Unique transaction identifier
     */
    @JsonProperty("hitRules")
    @java.lang.Override
    public List<HitRulesDetails> getHitRules() {
        return hitRules;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TransactionMonitoringResult && equalTo((TransactionMonitoringResult) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TransactionMonitoringResult other) {
        return transactionId.equals(other.transactionId)
                && status.equals(other.status)
                && riskScoreDetails.equals(other.riskScoreDetails)
                && executedRules.equals(other.executedRules)
                && hitRules.equals(other.hitRules);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.transactionId, this.status, this.riskScoreDetails, this.executedRules, this.hitRules);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TransactionIdStage builder() {
        return new Builder();
    }

    public interface TransactionIdStage {
        StatusStage transactionId(@NotNull String transactionId);

        Builder from(TransactionMonitoringResult other);
    }

    public interface StatusStage {
        _FinalStage status(@NotNull RuleAction status);
    }

    public interface _FinalStage {
        TransactionMonitoringResult build();

        _FinalStage riskScoreDetails(Optional<TransactionRiskScoringResult> riskScoreDetails);

        _FinalStage riskScoreDetails(TransactionRiskScoringResult riskScoreDetails);

        _FinalStage executedRules(List<ExecutedRulesResult> executedRules);

        _FinalStage addExecutedRules(ExecutedRulesResult executedRules);

        _FinalStage addAllExecutedRules(List<ExecutedRulesResult> executedRules);

        _FinalStage hitRules(List<HitRulesDetails> hitRules);

        _FinalStage addHitRules(HitRulesDetails hitRules);

        _FinalStage addAllHitRules(List<HitRulesDetails> hitRules);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements TransactionIdStage, StatusStage, _FinalStage {
        private String transactionId;

        private RuleAction status;

        private List<HitRulesDetails> hitRules = new ArrayList<>();

        private List<ExecutedRulesResult> executedRules = new ArrayList<>();

        private Optional<TransactionRiskScoringResult> riskScoreDetails = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(TransactionMonitoringResult other) {
            transactionId(other.getTransactionId());
            status(other.getStatus());
            riskScoreDetails(other.getRiskScoreDetails());
            executedRules(other.getExecutedRules());
            hitRules(other.getHitRules());
            return this;
        }

        /**
         * <p>Transaction ID that the results pertain to</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("transactionId")
        public StatusStage transactionId(@NotNull String transactionId) {
            this.transactionId = Objects.requireNonNull(transactionId, "transactionId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("status")
        public _FinalStage status(@NotNull RuleAction status) {
            this.status = Objects.requireNonNull(status, "status must not be null");
            return this;
        }

        /**
         * <p>Unique transaction identifier</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllHitRules(List<HitRulesDetails> hitRules) {
            this.hitRules.addAll(hitRules);
            return this;
        }

        /**
         * <p>Unique transaction identifier</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addHitRules(HitRulesDetails hitRules) {
            this.hitRules.add(hitRules);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "hitRules", nulls = Nulls.SKIP)
        public _FinalStage hitRules(List<HitRulesDetails> hitRules) {
            this.hitRules.clear();
            this.hitRules.addAll(hitRules);
            return this;
        }

        /**
         * <p>Unique transaction identifier</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllExecutedRules(List<ExecutedRulesResult> executedRules) {
            this.executedRules.addAll(executedRules);
            return this;
        }

        /**
         * <p>Unique transaction identifier</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addExecutedRules(ExecutedRulesResult executedRules) {
            this.executedRules.add(executedRules);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "executedRules", nulls = Nulls.SKIP)
        public _FinalStage executedRules(List<ExecutedRulesResult> executedRules) {
            this.executedRules.clear();
            this.executedRules.addAll(executedRules);
            return this;
        }

        @java.lang.Override
        public _FinalStage riskScoreDetails(TransactionRiskScoringResult riskScoreDetails) {
            this.riskScoreDetails = Optional.ofNullable(riskScoreDetails);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "riskScoreDetails", nulls = Nulls.SKIP)
        public _FinalStage riskScoreDetails(Optional<TransactionRiskScoringResult> riskScoreDetails) {
            this.riskScoreDetails = riskScoreDetails;
            return this;
        }

        @java.lang.Override
        public TransactionMonitoringResult build() {
            return new TransactionMonitoringResult(
                    transactionId, status, riskScoreDetails, executedRules, hitRules, additionalProperties);
        }
    }
}
