/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flagright.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.flagright.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TransactionMetadata.Builder.class)
public final class TransactionMetadata {
    private final Optional<List<BlockchainRisk>> blockchainRisk;

    private final Map<String, Object> additionalProperties;

    private TransactionMetadata(
            Optional<List<BlockchainRisk>> blockchainRisk, Map<String, Object> additionalProperties) {
        this.blockchainRisk = blockchainRisk;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return List of blockchain risk analyses from different providers
     */
    @JsonProperty("blockchainRisk")
    public Optional<List<BlockchainRisk>> getBlockchainRisk() {
        return blockchainRisk;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TransactionMetadata && equalTo((TransactionMetadata) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TransactionMetadata other) {
        return blockchainRisk.equals(other.blockchainRisk);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.blockchainRisk);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<BlockchainRisk>> blockchainRisk = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(TransactionMetadata other) {
            blockchainRisk(other.getBlockchainRisk());
            return this;
        }

        @JsonSetter(value = "blockchainRisk", nulls = Nulls.SKIP)
        public Builder blockchainRisk(Optional<List<BlockchainRisk>> blockchainRisk) {
            this.blockchainRisk = blockchainRisk;
            return this;
        }

        public Builder blockchainRisk(List<BlockchainRisk> blockchainRisk) {
            this.blockchainRisk = Optional.ofNullable(blockchainRisk);
            return this;
        }

        public TransactionMetadata build() {
            return new TransactionMetadata(blockchainRisk, additionalProperties);
        }
    }
}
