/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flagright.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.flagright.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UserBase.Builder.class)
public final class UserBase {
    private final String userId;

    private final double createdTimestamp;

    private final Map<String, Object> additionalProperties;

    private UserBase(String userId, double createdTimestamp, Map<String, Object> additionalProperties) {
        this.userId = userId;
        this.createdTimestamp = createdTimestamp;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Unique user ID
     */
    @JsonProperty("userId")
    public String getUserId() {
        return userId;
    }

    /**
     * @return Timestamp when userId is created
     */
    @JsonProperty("createdTimestamp")
    public double getCreatedTimestamp() {
        return createdTimestamp;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UserBase && equalTo((UserBase) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UserBase other) {
        return userId.equals(other.userId) && createdTimestamp == other.createdTimestamp;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.userId, this.createdTimestamp);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static UserIdStage builder() {
        return new Builder();
    }

    public interface UserIdStage {
        CreatedTimestampStage userId(@NotNull String userId);

        Builder from(UserBase other);
    }

    public interface CreatedTimestampStage {
        _FinalStage createdTimestamp(double createdTimestamp);
    }

    public interface _FinalStage {
        UserBase build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements UserIdStage, CreatedTimestampStage, _FinalStage {
        private String userId;

        private double createdTimestamp;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(UserBase other) {
            userId(other.getUserId());
            createdTimestamp(other.getCreatedTimestamp());
            return this;
        }

        /**
         * <p>Unique user ID</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("userId")
        public CreatedTimestampStage userId(@NotNull String userId) {
            this.userId = Objects.requireNonNull(userId, "userId must not be null");
            return this;
        }

        /**
         * <p>Timestamp when userId is created</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("createdTimestamp")
        public _FinalStage createdTimestamp(double createdTimestamp) {
            this.createdTimestamp = createdTimestamp;
            return this;
        }

        @java.lang.Override
        public UserBase build() {
            return new UserBase(userId, createdTimestamp, additionalProperties);
        }
    }
}
