/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flagright.api.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum UserRegistrationStatus {
    REGISTERED("REGISTERED"),

    UNREGISTERED("UNREGISTERED");

    private final String value;

    UserRegistrationStatus(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
