/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flagright.api.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum WalletNetwork {
    BITCOIN("BITCOIN"),

    ETHEREUM("ETHEREUM"),

    POLYGON("POLYGON"),

    BNB_SMART_CHAIN("BNB_SMART_CHAIN"),

    BNB_BEACON_CHAIN("BNB_BEACON_CHAIN"),

    ARBITRUM_L_2("ARBITRUM_L2"),

    SOLANA("SOLANA"),

    AVALANCHE_C_CHAIN("AVALANCHE_C_CHAIN"),

    TEZOS("TEZOS"),

    VICTION("VICTION"),

    LITECOIN("LITECOIN"),

    BITCOIN_CASH("BITCOIN_CASH"),

    RIPPLE("RIPPLE"),

    STELLAR("STELLAR"),

    EOS_PUBLIC("EOS_PUBLIC"),

    TRON("TRON"),

    CARDANO("CARDANO"),

    POLKADOT("POLKADOT"),

    NEAR_PROTOCOL("NEAR_PROTOCOL"),

    COSMOS("COSMOS"),

    DOGECOIN("DOGECOIN"),

    OPTIMISM_MAINNET("OPTIMISM_MAINNET"),

    FANTOM("FANTOM"),

    HEDERA("HEDERA"),

    ALGORAND("ALGORAND"),

    CELESTIA("CELESTIA");

    private final String value;

    WalletNetwork(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
