/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flagright.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.flagright.api.core.ObjectMappers;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = WebhookPepStatusDetails.Builder.class)
public final class WebhookPepStatusDetails {
    private final String userId;

    private final List<PepStatus> pepStatus;

    private final Map<String, Object> additionalProperties;

    private WebhookPepStatusDetails(
            String userId, List<PepStatus> pepStatus, Map<String, Object> additionalProperties) {
        this.userId = userId;
        this.pepStatus = pepStatus;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("userId")
    public String getUserId() {
        return userId;
    }

    @JsonProperty("pepStatus")
    public List<PepStatus> getPepStatus() {
        return pepStatus;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof WebhookPepStatusDetails && equalTo((WebhookPepStatusDetails) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(WebhookPepStatusDetails other) {
        return userId.equals(other.userId) && pepStatus.equals(other.pepStatus);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.userId, this.pepStatus);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static UserIdStage builder() {
        return new Builder();
    }

    public interface UserIdStage {
        _FinalStage userId(@NotNull String userId);

        Builder from(WebhookPepStatusDetails other);
    }

    public interface _FinalStage {
        WebhookPepStatusDetails build();

        _FinalStage pepStatus(List<PepStatus> pepStatus);

        _FinalStage addPepStatus(PepStatus pepStatus);

        _FinalStage addAllPepStatus(List<PepStatus> pepStatus);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements UserIdStage, _FinalStage {
        private String userId;

        private List<PepStatus> pepStatus = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(WebhookPepStatusDetails other) {
            userId(other.getUserId());
            pepStatus(other.getPepStatus());
            return this;
        }

        @java.lang.Override
        @JsonSetter("userId")
        public _FinalStage userId(@NotNull String userId) {
            this.userId = Objects.requireNonNull(userId, "userId must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllPepStatus(List<PepStatus> pepStatus) {
            this.pepStatus.addAll(pepStatus);
            return this;
        }

        @java.lang.Override
        public _FinalStage addPepStatus(PepStatus pepStatus) {
            this.pepStatus.add(pepStatus);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "pepStatus", nulls = Nulls.SKIP)
        public _FinalStage pepStatus(List<PepStatus> pepStatus) {
            this.pepStatus.clear();
            this.pepStatus.addAll(pepStatus);
            return this;
        }

        @java.lang.Override
        public WebhookPepStatusDetails build() {
            return new WebhookPepStatusDetails(userId, pepStatus, additionalProperties);
        }
    }
}
