/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flagright.api.resources.consumerusers.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.flagright.api.core.ObjectMappers;
import com.flagright.api.types.BooleanString;
import com.flagright.api.types.User;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ConsumerUsersCreateRequest.Builder.class)
public final class ConsumerUsersCreateRequest {
    private final Optional<BooleanString> lockCraRiskLevel;

    private final Optional<BooleanString> lockKycRiskLevel;

    private final Optional<BooleanString> validateUserId;

    private final User body;

    private final Map<String, Object> additionalProperties;

    private ConsumerUsersCreateRequest(
            Optional<BooleanString> lockCraRiskLevel,
            Optional<BooleanString> lockKycRiskLevel,
            Optional<BooleanString> validateUserId,
            User body,
            Map<String, Object> additionalProperties) {
        this.lockCraRiskLevel = lockCraRiskLevel;
        this.lockKycRiskLevel = lockKycRiskLevel;
        this.validateUserId = validateUserId;
        this.body = body;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Boolean string whether Flagright should lock the CRA risk level for the user.
     */
    @JsonProperty("lockCraRiskLevel")
    public Optional<BooleanString> getLockCraRiskLevel() {
        return lockCraRiskLevel;
    }

    /**
     * @return Boolean string whether Flagright should lock the KYC risk level for the user.
     */
    @JsonProperty("lockKycRiskLevel")
    public Optional<BooleanString> getLockKycRiskLevel() {
        return lockKycRiskLevel;
    }

    /**
     * @return Boolean string whether Flagright should validate the userId
     */
    @JsonProperty("validateUserId")
    public Optional<BooleanString> getValidateUserId() {
        return validateUserId;
    }

    @JsonProperty("body")
    public User getBody() {
        return body;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ConsumerUsersCreateRequest && equalTo((ConsumerUsersCreateRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ConsumerUsersCreateRequest other) {
        return lockCraRiskLevel.equals(other.lockCraRiskLevel)
                && lockKycRiskLevel.equals(other.lockKycRiskLevel)
                && validateUserId.equals(other.validateUserId)
                && body.equals(other.body);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.lockCraRiskLevel, this.lockKycRiskLevel, this.validateUserId, this.body);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static BodyStage builder() {
        return new Builder();
    }

    public interface BodyStage {
        _FinalStage body(@NotNull User body);

        Builder from(ConsumerUsersCreateRequest other);
    }

    public interface _FinalStage {
        ConsumerUsersCreateRequest build();

        _FinalStage lockCraRiskLevel(Optional<BooleanString> lockCraRiskLevel);

        _FinalStage lockCraRiskLevel(BooleanString lockCraRiskLevel);

        _FinalStage lockKycRiskLevel(Optional<BooleanString> lockKycRiskLevel);

        _FinalStage lockKycRiskLevel(BooleanString lockKycRiskLevel);

        _FinalStage validateUserId(Optional<BooleanString> validateUserId);

        _FinalStage validateUserId(BooleanString validateUserId);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements BodyStage, _FinalStage {
        private User body;

        private Optional<BooleanString> validateUserId = Optional.empty();

        private Optional<BooleanString> lockKycRiskLevel = Optional.empty();

        private Optional<BooleanString> lockCraRiskLevel = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ConsumerUsersCreateRequest other) {
            lockCraRiskLevel(other.getLockCraRiskLevel());
            lockKycRiskLevel(other.getLockKycRiskLevel());
            validateUserId(other.getValidateUserId());
            body(other.getBody());
            return this;
        }

        @java.lang.Override
        @JsonSetter("body")
        public _FinalStage body(@NotNull User body) {
            this.body = Objects.requireNonNull(body, "body must not be null");
            return this;
        }

        /**
         * <p>Boolean string whether Flagright should validate the userId</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage validateUserId(BooleanString validateUserId) {
            this.validateUserId = Optional.ofNullable(validateUserId);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "validateUserId", nulls = Nulls.SKIP)
        public _FinalStage validateUserId(Optional<BooleanString> validateUserId) {
            this.validateUserId = validateUserId;
            return this;
        }

        /**
         * <p>Boolean string whether Flagright should lock the KYC risk level for the user.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage lockKycRiskLevel(BooleanString lockKycRiskLevel) {
            this.lockKycRiskLevel = Optional.ofNullable(lockKycRiskLevel);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "lockKycRiskLevel", nulls = Nulls.SKIP)
        public _FinalStage lockKycRiskLevel(Optional<BooleanString> lockKycRiskLevel) {
            this.lockKycRiskLevel = lockKycRiskLevel;
            return this;
        }

        /**
         * <p>Boolean string whether Flagright should lock the CRA risk level for the user.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage lockCraRiskLevel(BooleanString lockCraRiskLevel) {
            this.lockCraRiskLevel = Optional.ofNullable(lockCraRiskLevel);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "lockCraRiskLevel", nulls = Nulls.SKIP)
        public _FinalStage lockCraRiskLevel(Optional<BooleanString> lockCraRiskLevel) {
            this.lockCraRiskLevel = lockCraRiskLevel;
            return this;
        }

        @java.lang.Override
        public ConsumerUsersCreateRequest build() {
            return new ConsumerUsersCreateRequest(
                    lockCraRiskLevel, lockKycRiskLevel, validateUserId, body, additionalProperties);
        }
    }
}
