/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flagright.api.errors;

import com.flagright.api.core.FlagrightApiException;
import com.flagright.api.types.ApiErrorResponse;
import okhttp3.Response;

public final class ConflictError extends FlagrightApiException {
    /**
     * The body of the response that triggered the exception.
     */
    private final ApiErrorResponse body;

    public ConflictError(ApiErrorResponse body) {
        super("ConflictError", 409, body);
        this.body = body;
    }

    public ConflictError(ApiErrorResponse body, Response rawResponse) {
        super("ConflictError", 409, body, rawResponse);
        this.body = body;
    }

    /**
     * @return the body
     */
    @java.lang.Override
    public ApiErrorResponse body() {
        return this.body;
    }
}
