/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flagright.api.resources.batch.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.flagright.api.core.ObjectMappers;
import com.flagright.api.types.Business;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = BusinessBatchRequest.Builder.class)
public final class BusinessBatchRequest {
    private final Optional<String> batchId;

    private final List<Business> data;

    private final Map<String, Object> additionalProperties;

    private BusinessBatchRequest(
            Optional<String> batchId, List<Business> data, Map<String, Object> additionalProperties) {
        this.batchId = batchId;
        this.data = data;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("batchId")
    public Optional<String> getBatchId() {
        return batchId;
    }

    @JsonProperty("data")
    public List<Business> getData() {
        return data;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof BusinessBatchRequest && equalTo((BusinessBatchRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(BusinessBatchRequest other) {
        return batchId.equals(other.batchId) && data.equals(other.data);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.batchId, this.data);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> batchId = Optional.empty();

        private List<Business> data = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(BusinessBatchRequest other) {
            batchId(other.getBatchId());
            data(other.getData());
            return this;
        }

        @JsonSetter(value = "batchId", nulls = Nulls.SKIP)
        public Builder batchId(Optional<String> batchId) {
            this.batchId = batchId;
            return this;
        }

        public Builder batchId(String batchId) {
            this.batchId = Optional.ofNullable(batchId);
            return this;
        }

        @JsonSetter(value = "data", nulls = Nulls.SKIP)
        public Builder data(List<Business> data) {
            this.data.clear();
            this.data.addAll(data);
            return this;
        }

        public Builder addData(Business data) {
            this.data.add(data);
            return this;
        }

        public Builder addAllData(List<Business> data) {
            this.data.addAll(data);
            return this;
        }

        public BusinessBatchRequest build() {
            return new BusinessBatchRequest(batchId, data, additionalProperties);
        }
    }
}
