/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flagright.api.resources.batch.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.flagright.api.core.ObjectMappers;
import com.flagright.api.types.BooleanString;
import com.flagright.api.types.Transaction;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TransactionBatchRequest.Builder.class)
public final class TransactionBatchRequest {
    private final Optional<BooleanString> validateOriginUserId;

    private final Optional<BooleanString> validateDestinationUserId;

    private final Optional<String> batchId;

    private final List<Transaction> data;

    private final Map<String, Object> additionalProperties;

    private TransactionBatchRequest(
            Optional<BooleanString> validateOriginUserId,
            Optional<BooleanString> validateDestinationUserId,
            Optional<String> batchId,
            List<Transaction> data,
            Map<String, Object> additionalProperties) {
        this.validateOriginUserId = validateOriginUserId;
        this.validateDestinationUserId = validateDestinationUserId;
        this.batchId = batchId;
        this.data = data;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Boolean string whether Flagright should validate if provided originUserId exist. True by default
     */
    @JsonProperty("validateOriginUserId")
    public Optional<BooleanString> getValidateOriginUserId() {
        return validateOriginUserId;
    }

    /**
     * @return Boolean string whether Flagright should validate if provided destinationUserId exist. True by default
     */
    @JsonProperty("validateDestinationUserId")
    public Optional<BooleanString> getValidateDestinationUserId() {
        return validateDestinationUserId;
    }

    @JsonProperty("batchId")
    public Optional<String> getBatchId() {
        return batchId;
    }

    @JsonProperty("data")
    public List<Transaction> getData() {
        return data;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TransactionBatchRequest && equalTo((TransactionBatchRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TransactionBatchRequest other) {
        return validateOriginUserId.equals(other.validateOriginUserId)
                && validateDestinationUserId.equals(other.validateDestinationUserId)
                && batchId.equals(other.batchId)
                && data.equals(other.data);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.validateOriginUserId, this.validateDestinationUserId, this.batchId, this.data);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<BooleanString> validateOriginUserId = Optional.empty();

        private Optional<BooleanString> validateDestinationUserId = Optional.empty();

        private Optional<String> batchId = Optional.empty();

        private List<Transaction> data = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(TransactionBatchRequest other) {
            validateOriginUserId(other.getValidateOriginUserId());
            validateDestinationUserId(other.getValidateDestinationUserId());
            batchId(other.getBatchId());
            data(other.getData());
            return this;
        }

        @JsonSetter(value = "validateOriginUserId", nulls = Nulls.SKIP)
        public Builder validateOriginUserId(Optional<BooleanString> validateOriginUserId) {
            this.validateOriginUserId = validateOriginUserId;
            return this;
        }

        public Builder validateOriginUserId(BooleanString validateOriginUserId) {
            this.validateOriginUserId = Optional.ofNullable(validateOriginUserId);
            return this;
        }

        @JsonSetter(value = "validateDestinationUserId", nulls = Nulls.SKIP)
        public Builder validateDestinationUserId(Optional<BooleanString> validateDestinationUserId) {
            this.validateDestinationUserId = validateDestinationUserId;
            return this;
        }

        public Builder validateDestinationUserId(BooleanString validateDestinationUserId) {
            this.validateDestinationUserId = Optional.ofNullable(validateDestinationUserId);
            return this;
        }

        @JsonSetter(value = "batchId", nulls = Nulls.SKIP)
        public Builder batchId(Optional<String> batchId) {
            this.batchId = batchId;
            return this;
        }

        public Builder batchId(String batchId) {
            this.batchId = Optional.ofNullable(batchId);
            return this;
        }

        @JsonSetter(value = "data", nulls = Nulls.SKIP)
        public Builder data(List<Transaction> data) {
            this.data.clear();
            this.data.addAll(data);
            return this;
        }

        public Builder addData(Transaction data) {
            this.data.add(data);
            return this;
        }

        public Builder addAllData(List<Transaction> data) {
            this.data.addAll(data);
            return this;
        }

        public TransactionBatchRequest build() {
            return new TransactionBatchRequest(
                    validateOriginUserId, validateDestinationUserId, batchId, data, additionalProperties);
        }
    }
}
