/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flagright.api.resources.batch;

import com.flagright.api.core.ClientOptions;
import com.flagright.api.core.RequestOptions;
import com.flagright.api.resources.batch.requests.BusinessBatchRequest;
import com.flagright.api.resources.batch.requests.BusinessUserEventBatchRequest;
import com.flagright.api.resources.batch.requests.ConsumerUserEventBatchRequest;
import com.flagright.api.resources.batch.requests.TransactionBatchRequest;
import com.flagright.api.resources.batch.requests.TransactionEventBatchRequest;
import com.flagright.api.resources.batch.requests.UserBatchRequest;
import com.flagright.api.types.BatchResponse;

public class BatchClient {
    protected final ClientOptions clientOptions;

    private final RawBatchClient rawClient;

    public BatchClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawBatchClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawBatchClient withRawResponse() {
        return this.rawClient;
    }

    public BatchResponse verifyTransaction(TransactionBatchRequest request) {
        return this.rawClient.verifyTransaction(request).body();
    }

    public BatchResponse verifyTransaction(TransactionBatchRequest request, RequestOptions requestOptions) {
        return this.rawClient.verifyTransaction(request, requestOptions).body();
    }

    public BatchResponse createTransactionEvents(TransactionEventBatchRequest request) {
        return this.rawClient.createTransactionEvents(request).body();
    }

    public BatchResponse createTransactionEvents(TransactionEventBatchRequest request, RequestOptions requestOptions) {
        return this.rawClient.createTransactionEvents(request, requestOptions).body();
    }

    public BatchResponse createConsumerUsers(UserBatchRequest request) {
        return this.rawClient.createConsumerUsers(request).body();
    }

    public BatchResponse createConsumerUsers(UserBatchRequest request, RequestOptions requestOptions) {
        return this.rawClient.createConsumerUsers(request, requestOptions).body();
    }

    public BatchResponse createBusinessUsers(BusinessBatchRequest request) {
        return this.rawClient.createBusinessUsers(request).body();
    }

    public BatchResponse createBusinessUsers(BusinessBatchRequest request, RequestOptions requestOptions) {
        return this.rawClient.createBusinessUsers(request, requestOptions).body();
    }

    public BatchResponse createConsumerUserEvents(ConsumerUserEventBatchRequest request) {
        return this.rawClient.createConsumerUserEvents(request).body();
    }

    public BatchResponse createConsumerUserEvents(
            ConsumerUserEventBatchRequest request, RequestOptions requestOptions) {
        return this.rawClient.createConsumerUserEvents(request, requestOptions).body();
    }

    public BatchResponse createBusinessUserEvents(BusinessUserEventBatchRequest request) {
        return this.rawClient.createBusinessUserEvents(request).body();
    }

    public BatchResponse createBusinessUserEvents(
            BusinessUserEventBatchRequest request, RequestOptions requestOptions) {
        return this.rawClient.createBusinessUserEvents(request, requestOptions).body();
    }
}
